window.MatGame = window.MatGame || {};

MatGame.CONFIG = Object.freeze({
  largura: 1280,
  altura: 720,
  gravidade: 1900,
  velocidade: 300,
  pulo: 680,
  debug: false,
  mundo: {
    larguraChunk: 960,
    gerarAdiante: 2200,
    intervaloDesafioChunks: 3,
    moedasPorChunk: 5,
    dificuldadeACada: 5,
    dificuldadeTempoSegundos: 55,
    retornoMaximo: 0.5,
    monstrosInicioMetros: 200,
    atiradoresInicioMetros: 500,
    monstroMolaMetros: 1000,
    monstroBumerangueMetros: 1500,
    monstroSombraMetros: 2000,
    chefeCadaMetros: 1000,
    chefeAtiradorMetros: 3000,
    congelanteMetros: 2500,
    aranhaMetros: 3000,
    plataformaHorizontalMetros: 1000,
    plataformaVerticalMetros: 3000,
    plataformaMovelAmplitudeHorizontal: 155,
    plataformaMovelAmplitudeVertical: 115,
    plataformaMovelVelocidadeHorizontal: 1.25,
    plataformaMovelVelocidadeVertical: 1.4,
    extremoInicioMetros: 10000,
    extremoCadaMetros: 1000
  },
  tempo: {
    inicial: 80,
    urgenciaAbaixo: 10,
    moeda: 1.5,
    estrela: 12,
    pisarBicho: 5,
    colisaoBicho: 3,
    mago: 30,
    magoDuracao: 10,
    magoMinimo: 90,
    magoMaximo: 180,
    fadaPrimeira: 65,
    fadaIntervalo: 90,
    fadaTempo: 15,
    fruta: 5,
    chefe: 30,
    colisaoChefe: 5,
    projetilChefe: 4,
    projetilChefeInicial: 4.2,
    projetilChefeMinimo: 1.8,
    congelamentoDuracao: 3,
    queda: 20,
    estrelaPoderDuracao: 10,
    estrelaPoderVelocidade: 1.45,
    estrelaPoderMinimo: 35,
    estrelaPoderMaximo: 65,
    respostaSemPressa: 5,
    erroPergunta: 3,
    fantasmaApos: 45,
    giganteMinimo: 45,
    giganteMaximo: 85,
    colisaoGigante: 12,
    projetil: 2,
    projetilIntervaloInicial: 3.6,
    projetilIntervaloMinimo: 1.3,
    projetilReducaoCadaMetros: 150,
    dragaoTirosPorRajada: 3,
    dragaoIntervaloRajada: 0.38,
    dragaoFogoDistancia: 720,
    dragaoFogoEsmaecerApos: 430,
    camufladoDistancia: 180,
    perguntaBonusMaximo: 30,
    respostaMuitoRapidaAte: 10,
    respostaRapidaAte: 20,
    bonusMuitoRapido: 10,
    bonusRapido: 8,
    bonusComCalma: 6
  },
  pontos: {
    moeda: 10,
    tabuada: 100,
    expressao: 100,
    dinheiro: 100,
    interpretacao: 150,
    calculo: 50,
    primeiraTentativa: 50,
    especial: 50,
    checkpoint: 200
  },
  categorias: { tabuada: 30, expressao: 25, dinheiro: 20, problema: 25 },
  cores: { ceu: '#13294b', ceu2: '#24527a', chao: '#38a169', ouro: '#ffd166', tinta: '#f7fafc' }
});
