MatGame.GameScene=class {
 constructor(app){this.app=app;this.ctx=app.canvas.getContext('2d');this.teclas={};this.plataformas=[];this.moedas=[];this.estacoes=[];this.obstaculos=[];this.checkpoints=[];this.fimGerado=0;this.camera=0;this.rodando=false;}
 iniciar(){this.rodando=true;this.app.pausado=false;this.jogador={x:90,y:460,w:38,h:56,vx:0,vy:0,noChao:false};this.gerarAte(3200);this.ouvir();this.ultimo=performance.now();requestAnimationFrame(t=>this.loop(t));}
 ouvir(){this.down=e=>{this.teclas[e.code]=true;if(e.code==='Escape')this.app.alternarPausa();};this.up=e=>this.teclas[e.code]=false;addEventListener('keydown',this.down);addEventListener('keyup',this.up);}
 destruir(){this.rodando=false;removeEventListener('keydown',this.down);removeEventListener('keyup',this.up);}
 gerarAte(x){while(this.fimGerado<x){const c=this.app.gerador.proximo(),base=this.fimGerado;for(const p of c.plataformas)this.plataformas.push({x:base+p[0],y:p[1],w:p[2],h:p[3]});for(let i=0;i<MatGame.CONFIG.mundo.moedasPorChunk;i++)this.moedas.push({x:base+160+i*130,y:390-(i%2)*70,r:11,ativa:true});for(const o of c.obstaculos||[])this.obstaculos.push({x:base+o[0],y:o[1],w:o[2],h:o[3]});if(c.estacao)this.estacoes.push({x:base+c.estacao[0],y:c.estacao[1],ativa:true});if(c.checkpoint)this.checkpoints.push({x:base+c.checkpoint[0],y:c.checkpoint[1],ativa:true});this.fimGerado+=c.largura;this.chunkAtual=c.id;}}
 loop(agora){if(!this.rodando)return;const dt=Math.min(.033,(agora-this.ultimo)/1000);this.ultimo=agora;if(!this.app.pausado)this.atualizar(dt);this.desenhar();requestAnimationFrame(t=>this.loop(t));}
 atualizar(dt){const j=this.jogador,c=MatGame.CONFIG;const esq=this.teclas.ArrowLeft||this.teclas.KeyA,dir=this.teclas.ArrowRight||this.teclas.KeyD;j.vx=(dir?c.velocidade:0)-(esq?c.velocidade:0);if((this.teclas.ArrowUp||this.teclas.KeyW||this.teclas.Space)&&j.noChao){j.vy=-c.pulo;j.noChao=false;}const anteriorY=j.y;j.vy+=c.gravidade*dt;j.x=Math.max(0,j.x+j.vx*dt);j.y+=j.vy*dt;j.noChao=false;for(const p of this.plataformas){if(j.x+j.w>p.x&&j.x<p.x+p.w&&anteriorY+j.h<=p.y+8&&j.y+j.h>=p.y&&j.vy>=0){j.y=p.y-j.h;j.vy=0;j.noChao=true;}}
 this.camera=Math.max(0,j.x-330);this.app.distancia=Math.max(this.app.distancia,Math.floor(j.x/10));this.gerarAte(j.x+c.mundo.gerarAdiante);for(const m of this.moedas)if(m.ativa&&this.toca(j,{x:m.x-m.r,y:m.y-m.r,w:m.r*2,h:m.r*2})){m.ativa=false;this.app.placar.adicionar(c.pontos.moeda);}for(const o of this.obstaculos)if(this.toca(j,o)){j.vx=-180;j.vy=-350;j.x-=35;this.app.placar.combo=0;}for(const cp of this.checkpoints)if(cp.ativa&&Math.abs(j.x-cp.x)<45){cp.ativa=false;this.app.placar.adicionar(c.pontos.checkpoint);}for(const e of this.estacoes)if(e.ativa&&Math.abs(j.x-e.x)<50){e.ativa=false;this.desafio();}if(j.y>800)MatGame.ResultScene.mostrar(this.app,'queda');this.app.atualizarHud();}
 toca(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
 desafio(){const cat=this.app.seletor.categoria(),q=this.app.seletor.selecionar(cat,this.app.gerador.dificuldade());this.app.questaoDebug=q;MatGame.ChallengeScene.mostrar(this.app,q,cat,()=>{this.app.panel.classList.add('hidden');this.app.pausado=false;});}
 desenhar(){const x=this.camera,ctx=this.ctx,w=this.app.canvas.width,h=this.app.canvas.height,g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#112c50');g.addColorStop(1,'#4e9cc0');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle='#ffffff18';for(let i=0;i<8;i++){const cx=((i*270-x*.15)%1500+1500)%1500;ctx.beginPath();ctx.arc(cx,120+i%3*65,50+i%2*30,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#184b55';ctx.beginPath();ctx.moveTo(0,620);for(let i=0;i<=w;i+=100)ctx.lineTo(i,510+Math.sin((i+x*.25)/130)*50);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();
 for(const p of this.plataformas){if(p.x-x>w||p.x+p.w-x<0)continue;ctx.fillStyle='#216e4e';ctx.fillRect(p.x-x,p.y,p.w,p.h);ctx.fillStyle='#63d471';ctx.fillRect(p.x-x,p.y,p.w,12);}for(const m of this.moedas)if(m.ativa){ctx.fillStyle='#ffd166';ctx.beginPath();ctx.arc(m.x-x,m.y,m.r,0,7);ctx.fill();ctx.strokeStyle='#fff2a8';ctx.lineWidth=3;ctx.stroke();}for(const o of this.obstaculos){ctx.fillStyle='#ef476f';ctx.beginPath();ctx.moveTo(o.x-x,o.y+o.h);ctx.lineTo(o.x+o.w/2-x,o.y);ctx.lineTo(o.x+o.w-x,o.y+o.h);ctx.fill();}for(const e of this.estacoes)if(e.ativa){ctx.fillStyle='#6ee7ff';ctx.fillRect(e.x-x-25,e.y-65,50,75);ctx.fillStyle='#102a43';ctx.font='bold 42px sans-serif';ctx.fillText('?',e.x-x-13,e.y-15);}for(const cp of this.checkpoints)if(cp.ativa){ctx.fillStyle='#ffd166';ctx.fillRect(cp.x-x,cp.y-70,8,90);ctx.font='35px sans-serif';ctx.fillText('★',cp.x-x+8,cp.y-40);}const j=this.jogador;ctx.fillStyle='#ff8c42';ctx.fillRect(j.x-x,j.y,j.w,j.h);ctx.fillStyle='#fff';ctx.fillRect(j.x-x+23,j.y+10,8,9);ctx.fillStyle='#102a43';ctx.fillRect(j.x-x+26,j.y+12,4,5);ctx.fillStyle='#ffd166';ctx.fillRect(j.x-x-5,j.y+42,18,14);if(this.app.debug){ctx.fillStyle='#000b';ctx.fillRect(12,650,500,55);ctx.fillStyle='#fff';ctx.font='18px monospace';ctx.fillText(`chunk=${this.chunkAtual} dificuldade=${this.app.gerador.dificuldade()} resposta=${this.app.questaoDebug?.resposta??'-'}`,20,682);}}
};
