const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.localStorage={d:{},getItem(k){return this.d[k]??null},setItem(k,v){this.d[k]=v}};
['js/config.js','js/game/seed.js','js/game/chunks.js','js/game/procedural.js','js/game/score.js','js/math/mathEngine.js'].forEach(f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f}));const banco=JSON.parse(fs.readFileSync('banco/conteudo.json'));
const resultados=[];function teste(nome,fn){fn();resultados.push('✓ '+nome)}
teste('cópia JavaScript está sincronizada com o JSON',()=>{const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('banco/conteudo.js','utf8'),sandbox);assert.deepStrictEqual(JSON.parse(JSON.stringify(sandbox.window.MatGameContent)),banco)});
teste('a mesma seed gera a mesma sequência',()=>assert.deepStrictEqual(new MatGame.Gerador('82741').sequencia(30),new MatGame.Gerador('82741').sequencia(30)));
teste('bancos possuem o conteúdo mínimo',()=>{assert(banco.tabuadas.length>=30);assert(banco.expressoes.length>=20);assert(banco.dinheiro.length>=20);assert(banco.problemas.length>=40)});
teste('respostas estão presentes e alternativas não se repetem',()=>{for(const grupo of ['tabuadas','expressoes','dinheiro','problemas'])for(const q of banco[grupo]){assert.strictEqual(new Set(q.alternativas).size,q.alternativas.length,q.id);assert(q.alternativas.includes(q.resposta),q.id);if(q.alternativasExpressao){assert.strictEqual(new Set(q.alternativasExpressao).size,q.alternativasExpressao.length,q.id);assert(q.alternativasExpressao.includes(q.expressao),q.id)}}});
teste('expressões respeitam prioridade operacional',()=>{for(const q of banco.expressoes){const valor=Function(`return ${q.pergunta.replaceAll('×','*')}`)();assert.strictEqual(valor,q.resposta,q.id)}});
teste('expressões dos problemas correspondem às respostas',()=>{for(const q of banco.problemas){const expr=q.expressao.replaceAll('×','*').replaceAll('÷','/');const valor=Function(`return ${expr}`)();assert.strictEqual(valor,q.resposta,q.id)}});
teste('bônus de tempo são progressivos e não punitivos',()=>{const t=MatGame.CONFIG.tempo;assert(t.inicial>=60);assert(t.moeda>0);assert(t.estrela>t.moeda);assert(t.bonusMuitoRapido>t.bonusRapido);assert(t.bonusRapido>t.bonusComCalma);assert(t.colisaoBicho<=5)});
teste('dificuldade temporal não altera chunks da seed',()=>{const a=new MatGame.Gerador('tempo'),b=new MatGame.Gerador('tempo');a.tempoDecorrido=999;assert.deepStrictEqual(a.sequencia(20),b.sequencia(20));assert(a.dificuldadeMotora()>=a.dificuldade())});
teste('dinheiro usa somente centavos inteiros',()=>{for(const p of banco.produtos)assert(Number.isInteger(p.precoCentavos));for(const q of banco.dinheiro){assert(Number.isInteger(q.resposta));q.alternativas.forEach(Number.isInteger)}});
teste('chunks têm entrada e saída compatíveis',()=>{for(const c of MatGame.CHUNKS){assert.strictEqual(c.largura,MatGame.CONFIG.mundo.larguraChunk);assert(Math.abs(c.pontoEntrada-c.pontoSaida)<=120);assert(c.plataformas.length)}});
teste('LocalStorage persiste e separa recordes',()=>{MatGame.Recordes.salvar('turma',{pontos:100,distancia:20,comboMaximo:2});assert.strictEqual(MatGame.Recordes.ler().turma.pontos,100)});
teste('pontuação máxima e aproveitamento são consistentes',()=>{const p=new MatGame.Placar();p.adicionar(10);p.responder('tabuada',false,100);assert.strictEqual(p.pontos,10);assert.strictEqual(p.maximo,110)});
teste('seletor evita repetição imediata',()=>{const s=new MatGame.SeletorQuestoes(banco,new MatGame.Seed('abc'));for(const cat of ['tabuada','expressao','dinheiro','problema']){let anterior='';for(let i=0;i<15;i++){const q=s.selecionar(cat,3);assert.notStrictEqual(q.id,anterior);anterior=q.id}}});
console.log(resultados.join('\n'));console.log(`\n${resultados.length} validações concluídas; ${Object.values(banco).reduce((n,x)=>n+x.length,0)} registros revisados.`);
